### ISSUE TITLE
Integrate changes from official driver

### ISSUE THREAD

**Issue by ysangkok** [coolshou/mt7610u#2]
An official driver was released on the 9th of September.

http://www.tp-link.com/lb/download/Archer-T2UH.html#Driver

**Comment by yesimxev** [comment]
That one is not installing, giving the error:
`/root/Downloads/Archer_T2UH_V1_150909/Driver/UTIL/os/linux/../../common/rt_os_util.c:1:0: error: code model kernel does not support PIC mode
`
And yours can't be compiled either, same error. Please help

**Comment by zipzit** [comment]
Did you guys see this?
http://topics.mediatek.com/en/downloads1/downloads/mt7610u-usb/


Anybody besides me trying to use this device on a raspberry pi, and totally not getting anywhere, fast?

**Comment by artv2007** [comment]
2 **zipzit**

For R-Pi you may try this driver https://github.com/chenhaiq/mt7610u_wifi_sta_v3002_dpo_20130916

**Comment by ysangkok** [comment]
Closing since I am now using another chip.
